# docker-compose up
# docker-compose up -d
version: "3"

services:
  kibana: 
    image: kibana:8.10.4
    container_name: kibana8
    restart: always
    ports:
      - 5601:5601
    extra_hosts:
      - "workstation:host-gateway"
    network_mode: "host"
